name: Train Model CI

on:
  push:
    branches: [master]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: MLProject/conda.yaml
          cache-environment: true
          init-shell: powershell
          post-cleanup: 'all'

      - name: Check Python & mlflow
        run: |
          which python
          python --version
          mlflow --version
        shell: pwsh

      - name: Mlflow run
        id: mlrun_step
        env:
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject/mlruns"
        run: |
          mlflow run MLProject --env-manager=local
        shell: pwsh

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@user.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto-trained model"
          git push
        shell: pwsh

      - name: Get Latest Run
        run: |
          echo "RUN_ID=${{ steps.mlrun_step.outputs.run_id }}"" >> $GITHUB_ENV
          echo "Found Run ID: ${{ env.RUN_ID }}"

      - name: Build docker image
        env:
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject/mlruns"
        run:  |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "covid19-diagnosis-image"
        shell: pwsh
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}

      - name: Tag Docker Image
        run:  |
          docker tag covid19-diagnosis-image ${{ secrets.DOCKER_HUB_USERNAME }}/covid19-diagnosis-image:latest
        shell: pwsh

      - name: Push Docker Image
        run:  |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/covid19-diagnosis-image:latest
        shell: pwsh

        

      
