name: Train Model CI

on:
  push:
    branches: [master]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: MLProject/conda.yaml
          cache-environment: true
          init-shell: powershell
          post-cleanup: 'all'

      - name: Check Python & mlflow
        run: |
          which python
          python --version
          mlflow --version
        shell: pwsh

      - name: Run Training
        run: |
          python MLProject/modelling.py
        shell: pwsh

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@user.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto-trained model [skip ci]"
          git push
        shell: pwsh

      - name: Get Latest Run
        run: |
          BASE_PATH="MLProject/MLProject/mlruns"
          TARGET_EXP="Covid19 Patient Symptoms Diagnosis Github"
          
          # Find the Experiment ID
          EXP_ID=$(grep -r "name: $TARGET_EXP" $BASE_PATH/*/meta.yaml | cut -d'/' -f4)
          
          # Find the newest directory that is NOT 'datasets'
          LATEST_RUN=$(ls -td $BASE_PATH/$EXP_ID/*/ | grep -v "datasets" | head -1 | xargs basename)
          
          echo "EXP_ID=$EXP_ID" >> $GITHUB_ENV
          echo "RUN_ID=$LATEST_RUN" >> $GITHUB_ENV
          
          echo "Found Experiment ID: $EXP_ID"
          echo "Found Run ID: $LATEST_RUN"

      - name: Build docker image
        env:
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject/MLProject/mlruns"
        run:  |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "covid19-diagnosis-image"
        shell: pwsh
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}

      - name: Tag Docker Image
        run:  |
          docker tag covid19-diagnosis-image ${{ secrets.DOCKER_HUB_USERNAME }}/covid19-diagnosis-image:latest
        shell: pwsh

      - name: Push Docker Image
        run:  |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/covid19-diagnosis-image:latest
        shell: pwsh

        

      
